name: testing
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_generative_ai: ^0.4.6
  http: ^1.2.2
  image_picker: ^1.1.2
  shared_preferences: ^2.5.2
  dotted_border: ^2.1.0
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.1
  share_plus: ^10.1.4
  flutter_card_swiper: ^7.0.2
  animate_do: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/happy.png
    - assets/images/angry.png
    - assets/images/sad.png
    - assets/images/step_1.gif
    - assets/images/step_2.gif
    - assets/images/pantun.png
    - assets/txt/joy-NRC-Emotion-Lexicon.txt
    - assets/txt/sadness-NRC-Emotion-Lexicon.txt
    - assets/txt/anger-NRC-Emotion-Lexicon.txt
    - assets/images/batik_element_top_right.png
    - assets/images/batik_element_bottom_left.png
